### ISSUE TITLE
Looks exactly what I am looking for...

### ISSUE THREAD

**Issue by robalexclark** [austinmcnicholas/Xpath-Module#1]
...except I can't open it in Mendix 9.x - any ideas how to get it to work with this version?

**Comment by austinmcnicholas** [comment]
Give me an hour and ill make a release for Mx9

**Comment by austinmcnicholas** [comment]
https://marketplace.mendix.com/link/component/117833

the Mx9 version is published

**Comment by robalexclark** [comment]
Thanks!
